# grid map origin point
grid_origin_point_x: 0.0
grid_origin_point_y: 0.0
grid_origin_point_z: 0.0

# number of grids of grid map on three axis direction
grid_map_x_size: 2000
grid_map_y_size: 4000
grid_map_z_size: 2000

# inflation number of grids
inflation_radius: 5

# size of a grid described in mm unit
resolution: 10.0

# path plan start position and speed
start_position_x: 1000.0
start_position_y: 1900.0
start_position_z: 1000.0
start_speed_x: 0.0
start_speed_y: 20.0
start_speed_z: 0.0

# init project map's angle range
init_proj_map_view_angle: 160
# step degree of latitude and longitude of init project map
init_proj_map_lati_step: 1.0
init_proj_map_longi_step: 2.0

# optimize project map's angle range
opt_proj_map_view_angle: 160
# step degree of latitude and longitude of optimize project map
opt_proj_map_lati_step: 1.0
opt_proj_map_longi_step: 2.0

# average speed
average_speed: 20.0

# max numbers of the project line of one project map
max_num_proj_line: 3

# max numbers of the project
max_num_proj: 2


