joint_number: 15
joint0_rigid1_length: 0.0
joint0_rigid2_length: 0.0
joint1_rigid1_length: 0.0
joint1_rigid2_length: 0.0
joint2_rigid1_length: 0.0
joint2_rigid2_length: 0.0
joint3_rigid1_length: 0.0
joint3_rigid2_length: 0.0
joint4_rigid1_length: 0.0
joint4_rigid2_length: 0.0
joint5_rigid1_length: 0.0
joint5_rigid2_length: 0.0
joint6_rigid1_length: 0.0
joint6_rigid2_length: 0.0
joint7_rigid1_length: 0.0
joint7_rigid2_length: 0.0
joint8_rigid1_length: 0.0
joint8_rigid2_length: 0.0
joint9_rigid1_length: 0.0
joint9_rigid2_length: 0.0
joint10_rigid1_length: 0.0
joint10_rigid2_length: 0.0
joint11_rigid1_length: 0.0
joint11_rigid2_length: 0.0
joint12_rigid1_length: 0.0
joint12_rigid2_length: 0.0
joint13_rigid1_length: 0.0
joint13_rigid2_length: 0.0
joint14_rigid1_length: 0.0
joint14_rigid2_length: 0.0
joint15_rigid1_length: 0.0
joint15_rigid2_length: 0.0
joint16_rigid1_length: 0.0
joint16_rigid2_length: 0.0
joint17_rigid1_length: 0.0
joint17_rigid2_length: 0.0
joint18_rigid1_length: 0.0
joint18_rigid2_length: 0.0
joint19_rigid1_length: 0.0
joint19_rigid2_length: 0.0

joint0_continuum_length: 100.0
joint1_continuum_length: 100.0
joint2_continuum_length: 100.0
joint3_continuum_length: 100.0
joint4_continuum_length: 100.0
joint5_continuum_length: 100.0
joint6_continuum_length: 100.0
joint7_continuum_length: 100.0
joint8_continuum_length: 100.0
joint9_continuum_length: 100.0
joint10_continuum_length: 100.0
joint11_continuum_length: 100.0
joint12_continuum_length: 100.0
joint13_continuum_length: 100.0
joint14_continuum_length: 100.0
joint15_continuum_length: 100.0
joint16_continuum_length: 100.0
joint17_continuum_length: 100.0
joint18_continuum_length: 100.0
joint19_continuum_length: 100.0

stroke_start_x: 0.0
stroke_start_y: 0.0
stroke_start_z: 0.0
stroke_end_x: 0.0
stroke_end_y: 0.0
stroke_end_z: 0.0
world_to_ref_pos_x: 0.0
world_to_ref_pos_y: 0.0
world_to_ref_pos_z: 0.0
world_to_ref_orien_x: 0.0
world_to_ref_orien_y: 0.0
world_to_ref_orien_z: 0.0
world_to_ref_orien_w: 1.0
speed_value: 10.0
sample_interval: 1.0 
# 权重
weight_position: 0.6345
weight_direction: 0.3655
# 关节角上下边界
alpha_lower_bound: -180.0
alpha_upper_bound: 180.0
theta_lower_bound: -90.0
theta_upper_bound: 90.0


