stroke_start_x: 0.0
stroke_start_y: 0.0
stroke_start_z: 0.0
stroke_end_x: 0.0
stroke_end_y: 0.0
stroke_end_z: 0.0
world_to_ref_pos_x: 0.0
world_to_ref_pos_y: 0.0
world_to_ref_pos_z: 0.0
world_to_ref_orien_x: 0.0
world_to_ref_orien_y: 0.0
world_to_ref_orien_z: 0.0
world_to_ref_orien_w: 1.0
speed_value: 10.0
sample_interval: 1.0 
