%YAML:1.0
---

Camera.order: 0
Camera.fx: 425.7142390419255
Camera.fy: 425.6839191852586
Camera.cx: 351.2690888495462
Camera.cy: 228.6889439881554

Camera.k1: 0.1779923377898677
Camera.k2: -0.2606148395041221
Camera.p1: 0.0005920453623228711
Camera.p2: 0.0003438450505359588
Camera.k3: 0.146467637676061

blueLower.1: 100
blueLower.2: 43
blueLower.3: 46
blueUpper.1: 149
blueUpper.2: 255
blueUpper.3: 255
greenLower.1: 50
greenLower.2: 43
greenLower.3: 46
greenUpper.1: 90
greenUpper.2: 255
greenUpper.3: 255
redLower.1: 150
redLower.2: 43
redLower.3: 46
redUpper.1: 180
redUpper.2: 255
redUpper.3: 255
redPlusUpper.1: 33
redPlusUpper.2: 255
redPlusUpper.3: 255 
redPlusLower.1: 0
redPlusLower.2: 255
redPlusLower.3: 255
whiteLower1: 0
whiteLower2: 0
whiteLower3: 221
whiteUpper1: 180
whiteUpper2: 30
whiteUpper3: 255

open_blue_kernel_size: 17
close_blue_kernel_size: 15
open_green_kernel_size: 5
close_green_kernel_size: 9
open_red_kernel_size: 5
close_red_kernel_size: 7

# 判断motionControl功能包程序是否编写完成的标志:
# 0 未完成
# 1 完成
flag_motionControlProgramHaveDone: 0

# model圆形检测参数值
model_dp: 2
model_minDist: 40
model_cannyUpThresh: 80
model_circleThresh: 140
model_minRadius: 30
model_maxRadius: 150

# 掩码膨胀结构体大小
dilateSize_mask: 14

# canny直线检测时边缘检测阈值
canny_threshLow: 40
canny_threshUp: 90

# 直线检测相关参数
lineThresh: 110
minLineLength: 180
maxLineGap: 13

# ransac参数所需的参数列表长度阈值
modelThresh: 200

# 最小共线阈值以及最大垂直阈值
minCosValueThresh_collineation: 0.97
maxCosValueThresh_vertical: 0.17

# 两帧圆之间的半径差阈值、圆心距离阈值
model_difference_radius_thresh: 14
model_distance_center_thresh: 20


# 圆形检测参数值
dp: 2
minDist: 80
cannyUpThresh: 80
circleThresh: 190
minRadius: 50
maxRadius: 300

# 两帧圆之间的半径差阈值、圆心距离阈值
difference_radius_thresh: 20
distance_center_thresh: 25

# 正视判断的cos阈值
cosValue_thresh: 0.99
model_cosValueThresh_planeNormAndCameraZaxis: 0.94

# 相机平面之间的距离阈值
distance_thresh: 320

# 大核闭运算核大小
model_bigCloseStructure_size: 19
# 连续检测圆形的列表长度阈值
circle_size_thresh: 5
# 腐蚀膨胀核大小
erodeStructure_size: 7
dilateStructure_size: 15
# model腐蚀膨胀核大小
# 用来预处理去除无关区域的腐蚀大小
model_erodeStructure_size1: 7
# 用来筛选特征点的区域腐蚀大小
model_erodeStructure_size2: 11
# 用来判定边缘检测时直线是否为检测平面区域内的膨胀大小
model_dilateStructure_size2: 20
pixelNum_translate: 20

# 圆检测时圆周上的点向圆外以及圆内的像素值
outCircleVal: 20
inCircleVal: 5

# 尺度因子列表长度阈值
scaleFactList_size_thresh: 160
# 尺度因子内点阈值
inlier_thresh_scaleFact: 60
# ransac尺度因子采样长度
sample_length: 6
# 好点概率
inlier_probability: 0.4
# 随机采样的长度
model_sample_length: 6
# 单个样本好点概率
model_inlier_probability: 0.4
# ransac内点阈值
inlier_thresh_centre: 5
inlier_thresh_normVec: 0.99
inlier_thresh_dirVec: 0.99

octoTree.resolution: 5

minNumBlueKeyPoint: 70
minNumGreenKeyPoint: 40
minNumRedKeyPoint: 40

minNumPlaneParam: 100

numIteration: 10000

numPlaneParamSubSet: 10

timesIteration_BlueD: 40
timesIteration_GreenD: 40
timesIteration_RedD: 40

timesRansacIterBlue: 1000
timesRansacIterGreen: 500
timesRansacIterRed: 800

numSampleBlue: 50
numSampleGreen: 40
numSampleRed: 30
numsubSampleBlue: 5
numsubSampleGreen: 5
numsubSampleRed: 5
numRansacIterBlue: 1500
numRansacIterGreen: 1000
numRansacIterRed: 500

cosValueTresh: 0.97

maxLengthPointCloudList: 10

threshToOptBlue: 50
threshToOptGreen: 40
threshToOptRed: 40