%YAML:1.0
---
# 该配置文件默认均为mm单位制尺度。
# 如需更改单位，可将scaleFact_mmToTarget配置为目标单位/mm单位。

Camera.order: 0
Camera.fx: 425.7142390419255
Camera.fy: 425.6839191852586
Camera.cx: 351.2690888495462
Camera.cy: 228.6889439881554

Camera.k1: 0.1779923377898677
Camera.k2: -0.2606148395041221
Camera.p1: 0.0005920453623228711
Camera.p2: 0.0003438450505359588
Camera.k3: 0.146467637676061

blueLower.1: 100
blueLower.2: 43
blueLower.3: 46
blueUpper.1: 149
blueUpper.2: 255
blueUpper.3: 255

open_blue_kernel_size: 17
close_blue_kernel_size: 15

# flag used in model packages, it's a flag that determine publish the global pcl or realtime local pcl model
# 1: global pcl model;
# 2: local pcl model
flag_pub_global_pcl: 1

# 判断motionControl功能包程序是否编写完成的标志:
# 0 未完成
# 1 完成
flag_motionControlProgramHaveDone: 0

# mm制尺度到实际应用尺度(eg: M ,scaleFact_mmToTarget: 0.001)的转换因子
scaleFact_mmToTarget: 1.0

# 局部可视点云的水平与竖直方向的角度阈值
horizontalAngleThresh_localPointCloud: 50
verticalAngleThresh_localPointCloud: 40

# 实时建图的视野范围
horizontal: 1000.0

# model圆形检测参数值
model_dp: 2
model_minDist: 40
model_cannyUpThresh: 80
model_circleThresh: 140
model_minRadius: 30
model_maxRadius: 150

# 掩码膨胀结构体大小
dilateSize_mask: 14

# canny直线检测时边缘检测阈值
canny_threshLow: 40
canny_threshUp: 90

# 直线检测相关参数
lineThresh: 110
minLineLength: 180
maxLineGap: 13

# ransac参数所需的参数列表长度阈值
modelThresh: 300

# 最小共线阈值以及最大垂直阈值
minCosValueThresh_collineation: 0.97
maxCosValueThresh_vertical: 0.17

# 两帧圆之间的半径差阈值、圆心距离阈值
model_difference_radius_thresh: 14
model_distance_center_thresh: 20
# 实际圆形半径
circleRadius: 100

# 建立点云模型时的步进值(mm)
buildPointStep: 4.0
# 整个模型的xyz轴尺寸(mm)
xSize: 440.0
ySize: 735.0
zSize: 440.0
frontToStructureSize1: 185.0
frontToStructureSize2: 410.0
structureGapSize1: 260.0
structureGapSize2: 250.0
# 对地图进行栅格化的xyz上下边界(mm)
xBoundLow: -1000.0
yBoundLow: -1000.0
zBoundLow: -500.0
xBoundUp: 1000.0
yBoundUp: 1000.0
zBoundUp: 1500.0
# 占据网格的分辨率大小(mm)
gridResolution: 10.0

# 圆形检测参数值
dp: 2
minDist: 80
cannyUpThresh: 80
circleThresh: 190
minRadius: 50
maxRadius: 300

# 两帧圆之间的半径差阈值、圆心距离阈值
difference_radius_thresh: 20
distance_center_thresh: 25

# 正视判断的cos阈值
cosValue_thresh: 0.988
model_cosValueThresh_planeNormAndCameraZaxis: 0.96

# 相机平面之间的距离阈值
distance_thresh: 320.0

# 大核闭运算核大小
model_bigCloseStructure_size: 19
# 连续检测圆形的列表长度阈值
circle_size_thresh: 5
# 腐蚀膨胀核大小
erodeStructure_size: 7
dilateStructure_size: 15
# model腐蚀膨胀核大小
# 用来预处理去除无关区域的腐蚀大小
model_erodeStructure_size1: 7
# 用来筛选特征点的区域腐蚀大小
model_erodeStructure_size2: 11
# 用来判定边缘检测时直线是否为检测平面区域内的膨胀大小
model_dilateStructure_size2: 20
pixelNum_translate: 20

# 开始改变阈值的循环次数占总迭代次数的比例
scale_startLoopCountTochangeInlierThresh: 0.1

# 圆检测时圆周上的点向圆外以及圆内的像素值
outCircleVal: 20
inCircleVal: 5

# 尺度因子列表长度阈值
scaleFactList_size_thresh: 160
# 尺度因子内点阈值
inlier_thresh_scaleFact: 60.0
# ransac尺度因子采样长度
sample_length: 6
# 好点概率
inlier_probability: 0.4
# 随机采样的长度
model_sample_length: 6
# 单个样本好点概率
model_inlier_probability: 0.35
# ransac内点阈值
inlier_thresh_centre: 3.0
inlier_thresh_normVec: 0.9980
inlier_thresh_dirVec: 0.9980
# 圆心位置内点阈值的自适应增量
adaptiveIncrement_inlier_thresh_centre: 0.15
adaptiveIncrement_inlier_thresh_normVec: 0.0015
adaptiveIncrement_inlier_thresh_dirVec: 0.0015
# pcl点云拟合平面时内点的距离阈值
distanceThresh_plandAndPoint: 2.80

# 拟合平面时的点云数量阈值
mapPointNumThresh: 90

octoTree.resolution: 5.0

numIteration: 10000

cosValueTresh: 0.97

# TODO: 
T_camera_to_tool: 
  rows: 4
  cols: 4
  dt: d
  data: [0.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 0.0,
         0.0, 0.0, 0.0, 0.0]

goal_point_position_x: 1070.0
goal_point_position_y: 1680.0
goal_point_position_z: 970.0

translation_obs_to_world_x: 1000.0
translation_obs_to_world_y: 2000.0
translation_obs_to_world_z: 1000.0

